### PR TITLE
Initdb

### PR DESCRIPTION
**Pull request by rgutierrezs**
Branch "initdb" created to change the DB initialization process. "caom2" schema was hardcoded in the SQL table creation/update scripts, so the destination schema provided in the command line was ignored. Changes done to modify this behaviour.

NOTE: The "initdb" branch was created from ESDC trunk on September 27. Some changes where done on the ESDC trunk before that date, and are subsequently reflected in the pull request as modifications to the CADC trunk.

### CODE REVIEW

**Comment by rgutierrezs** [comment]
About the pull request procedure, we absolutely agree. We reached the same conclusion after seeing that the initdb branch was not containing uniquely the hardcoded schema changes. That will be adopted for future PRs. No problem in waiting for the PR 48 to be merged.

**Comment by rgutierrezs** [comment]
I merged the opencadc/master branch into esdc/initdb branch. Are there any pending actions from our side?

**Comment by pdowler** [comment]
There are till many changes unrelated to the initdb change and some look like they are removing things that were just added (eg the change in .travis.yml) so conflicts were probably not resolved as expected in those files. At least since the travis setup was changed and checkstyle did not actually run I cannot proceed. 

From a "git magic" point of view I'm not sure how to proceed. I would probably make a new clone from master and manually copy in the changed files in caom2persistence (just the version package and resources)... you might just copy the sql files and make the code changes manually (again) since it is only a few lines in InitDatabase -- that way the checkstyle changes would not have to be redone and possibly produce large diffs that obscure the real changes.

**Comment by rgutierrezs** [comment]
Will create a new branch for initdb changes from a fresh fork of CADC master branch. I will create a new pull request from that. Closing this one.

**Pull request closed without merging**
